"""Unit tests for Stage 12 synthesis tools.
"""

import unittest
from schemas.contracts import (
    EvidencePackage,
    CausalityPackage,
    CounterfactualPackage,
    SkepticPackage,
    FinalReport,
    RiskFactor,
    Citation,
    Contributor,
    Scenario,
)
from tools.synthesis import generate_final_report


class TestSynthesisLayer(unittest.TestCase):
    """Test suite for deterministic synthesis report creation in tools/synthesis.py."""

    def setUp(self) -> None:
        """Set up standard reasoning packages for testing."""
        # 1. Evidence
        cit = Citation(source="WHO Guidelines", title="Preventative Oncology", year=2021)
        self.evidence = EvidencePackage(
            risk_factors=[
                RiskFactor(factor="Tobacco Smoke Exposure", evidence_strength="high", evidence_score=0.95, source_count=12)
            ],
            citations=[cit],
            retrieved_documents=["doc1"]
        )

        # 2. Causality
        cont = Contributor(factor="Tobacco Smoke Exposure", rank=1, reason="Strong correlation with lung tumors")
        self.causality = CausalityPackage(
            ranked_contributors=[cont],
            primary_drivers=["Tobacco Smoke Exposure"],
            causal_confidence="high"
        )

        # 3. Counterfactual
        sc = Scenario(scenario_id="S1", change="Cessation of tobacco", expected_effect="high", reasoning="stops damage")
        self.counterfactual = CounterfactualPackage(
            scenarios=[sc],
            comparisons=[]
        )

        # 4. Skeptic
        self.skeptic = SkepticPackage(
            confidence="medium",
            uncertainties=["Dosimetry is unquantified"],
            limitations=["Self-reported exposures"],
            conflicting_evidence=[],
            missing_information=[]
        )

    def test_final_report_generation(self) -> None:
        """Verifies report generation returns a valid FinalReport schema object."""
        report = generate_final_report(
            self.evidence,
            self.causality,
            self.counterfactual,
            self.skeptic
        )

        self.assertIsInstance(report, FinalReport)

        # 1. Top contributor population
        self.assertEqual(report.top_contributors, ["Tobacco Smoke Exposure"])

        # 2. Evidence summary creation
        self.assertIn("Tobacco Smoke Exposure", report.evidence_summary)
        self.assertIn("high' confidence", report.evidence_summary)

        # 3. Counterfactual summary creation
        self.assertIn("Cessation of tobacco", report.counterfactual_summary)

        # 4. Limitation extraction
        self.assertIn("Self-reported exposures", report.limitations)
        self.assertIn("Dosimetry is unquantified", report.limitations)

        # 5. Citations and Confidence
        self.assertEqual(len(report.citations), 1)
        self.assertEqual(report.citations[0].source, "WHO Guidelines")
        self.assertEqual(report.confidence, "medium")

        # 6. Safety disclaimer inclusion
        self.assertIn("Disclaimer: This report is generated by an artificial intelligence assistant", report.safety_disclaimer)
        self.assertIn("not medical advice", report.safety_disclaimer)
        self.assertIn("does not replace consultation", report.safety_disclaimer)


if __name__ == "__main__":
    unittest.main()
