"""Unit tests for Stage 12 synthesis tools.
"""

import unittest
from schemas.contracts import (
    PatientProfile,
    EvidencePackage,
    CausalityPackage,
    CounterfactualPackage,
    SkepticPackage,
    FinalReport,
    RiskFactor,
    Citation,
    Contributor,
    Scenario,
)
from tools.synthesis import generate_final_report


class TestSynthesisLayer(unittest.TestCase):
    """Test suite for deterministic synthesis report creation in tools/synthesis.py."""

    def setUp(self) -> None:
        """Set up standard reasoning packages for testing."""
        # 1. Evidence
        cit = Citation(source="WHO Guidelines", title="Preventative Oncology", year=2021)
        self.evidence = EvidencePackage(
            risk_factors=[
                RiskFactor(factor="Tobacco Smoke Exposure", evidence_strength="high", evidence_score=0.95, source_count=12)
            ],
            citations=[cit],
            retrieved_documents=["doc1"]
        )

        # 2. Causality
        cont = Contributor(factor="Tobacco Smoke Exposure", rank=1, reason="Strong correlation with lung tumors")
        self.causality = CausalityPackage(
            ranked_contributors=[cont],
            primary_drivers=["Tobacco Smoke Exposure"],
            causal_confidence="high"
        )

        # 3. Counterfactual
        sc = Scenario(scenario_id="S1", change="Cessation of tobacco", expected_effect="high", reasoning="stops damage")
        self.counterfactual = CounterfactualPackage(
            scenarios=[sc],
            comparisons=[]
        )

        # 4. Skeptic
        self.skeptic = SkepticPackage(
            confidence="medium",
            uncertainties=["Dosimetry is unquantified"],
            limitations=["Self-reported exposures"],
            conflicting_evidence=[],
            missing_information=[]
        )

    def test_final_report_generation(self) -> None:
        """Verifies report generation returns a valid FinalReport schema object."""
        profile = PatientProfile(
            session_id="session_synthesis_test",
            age=45,
            sex="male",
            bmi=24.5,
            smoking_status="never",
            smoking_years=0,
            alcohol_use="none",
            physical_activity="medium",
            diet_quality="medium",
            sun_exposure="low",
            occupation="Office worker",
            environmental_exposure=[],
            family_history=False,
            known_mutations=[],
            previous_cancer_history=False,
        )
        report = generate_final_report(
            self.evidence,
            self.causality,
            self.counterfactual,
            self.skeptic,
            profile=profile
        )

        self.assertIsInstance(report, FinalReport)

        # 1. Top contributor population
        self.assertEqual(report.top_contributors, ["Tobacco Smoke Exposure"])

        # 2. Evidence summary creation
        self.assertIn("Tobacco Smoke Exposure", report.evidence_summary)
        self.assertIn("high' confidence", report.evidence_summary)

        # 3. Counterfactual summary creation
        self.assertIn("Cessation of tobacco", report.counterfactual_summary)

        # 4. Limitation extraction
        self.assertIn("Self-reported exposures", report.limitations)
        self.assertIn("Dosimetry is unquantified", report.limitations)

        # 5. Citations and Confidence
        self.assertEqual(len(report.citations), 1)
        self.assertEqual(report.citations[0].source, "WHO Guidelines")
        self.assertEqual(report.confidence, "medium")

        self.assertIn("Disclaimer: This report is generated by an artificial intelligence assistant", report.safety_disclaimer)
        self.assertIn("not medical advice", report.safety_disclaimer)
        self.assertIn("does not replace consultation", report.safety_disclaimer)

    def test_synthesis_profiles(self) -> None:
        """Verifies structured clinical reports across various profiles (Healthy, Smoking, Obesity, BRCA mutation, Mixed lifestyle, Previous cancer history)."""
        from schemas.contracts import PatientProfile
        
        # 1. Healthy Profile
        profile_healthy = PatientProfile(
            session_id="healthy", age=25, sex="female", bmi=21.5,
            smoking_status="never", smoking_years=0, alcohol_use="none",
            physical_activity="high", diet_quality="high", sun_exposure="low",
            occupation="office", environmental_exposure=[], family_history=False,
            known_mutations=[], previous_cancer_history=False
        )
        evidence_healthy = EvidencePackage(
            risk_factors=[RiskFactor(factor="General Environmental Baseline", evidence_strength="low", evidence_score=0.20, source_count=1)],
            citations=[Citation(source="Oncology Letters", title="Baseline Cancer Risks", year=2021)],
            retrieved_documents=[]
        )
        causality_healthy = CausalityPackage(
            ranked_contributors=[Contributor(factor="General Environmental Baseline", rank=1, reason="Aging baseline risk")],
            primary_drivers=["General Environmental Baseline"],
            causal_confidence="low"
        )
        cf_healthy = CounterfactualPackage(scenarios=[], comparisons=[])
        sk_healthy = SkepticPackage(
            confidence="low", uncertainties=["Baseline environmental interactions are poorly quantified."],
            limitations=["Generic baseline risk"], conflicting_evidence=[], missing_information=[]
        )

        rep_healthy = generate_final_report(evidence_healthy, causality_healthy, cf_healthy, sk_healthy, profile_healthy)
        self.assertIn("1. Patient Risk Summary", rep_healthy.evidence_summary)
        self.assertIn("predominantly environmental risk drivers", rep_healthy.evidence_summary)
        self.assertIn("General Environmental Baseline", rep_healthy.evidence_summary)

        # 2. Smoking Profile
        profile_smoking = PatientProfile(
            session_id="smoker", age=45, sex="male", bmi=23.0,
            smoking_status="active", smoking_years=25, alcohol_use="none",
            physical_activity="high", diet_quality="high", sun_exposure="low",
            occupation="office", environmental_exposure=[], family_history=False,
            known_mutations=[], previous_cancer_history=False
        )
        evidence_smoking = EvidencePackage(
            risk_factors=[RiskFactor(factor="Tobacco Smoke Exposure", evidence_strength="high", evidence_score=0.96, source_count=15)],
            citations=[Citation(source="BMJ", title="Tobacco Carcinogenesis", year=2018)],
            retrieved_documents=[]
        )
        causality_smoking = CausalityPackage(
            ranked_contributors=[Contributor(factor="Tobacco Smoke Exposure", rank=1, reason="Strong correlation with lung tumors")],
            primary_drivers=["Tobacco Smoke Exposure"],
            causal_confidence="high"
        )
        cf_smoking = CounterfactualPackage(
            scenarios=[Scenario(scenario_id="S_smk", change="Cessation of tobacco smoking", expected_effect="high", reasoning="Stops cumulative lung cell damage")],
            comparisons=[]
        )
        sk_smoking = SkepticPackage(
            confidence="high", uncertainties=["Potential Confounder: self-reported intensity"],
            limitations=["Self-reported smoking history"], conflicting_evidence=[], missing_information=[]
        )

        rep_smoking = generate_final_report(evidence_smoking, causality_smoking, cf_smoking, sk_smoking, profile_smoking)
        self.assertIn("predominantly lifestyle-related risk drivers", rep_smoking.evidence_summary)
        self.assertIn("Type: Modifiable", rep_smoking.evidence_summary)
        self.assertIn("Cessation of tobacco smoking", rep_smoking.counterfactual_summary)

        # 3. Obesity Profile
        profile_obesity = PatientProfile(
            session_id="obese", age=50, sex="female", bmi=34.0,
            smoking_status="never", smoking_years=0, alcohol_use="none",
            physical_activity="medium", diet_quality="low", sun_exposure="low",
            occupation="office", environmental_exposure=[], family_history=False,
            known_mutations=[], previous_cancer_history=False
        )
        evidence_obesity = EvidencePackage(
            risk_factors=[
                RiskFactor(factor="Obesity-related Cancer Risk", evidence_strength="high", evidence_score=0.85, source_count=8),
                RiskFactor(factor="Poor Dietary Pattern", evidence_strength="medium", evidence_score=0.60, source_count=4)
            ],
            citations=[Citation(source="JAMA", title="Obesity and Cancer", year=2019)],
            retrieved_documents=[]
        )
        causality_obesity = CausalityPackage(
            ranked_contributors=[
                Contributor(factor="Obesity-related Cancer Risk", rank=1, reason="Chronic inflammatory state"),
                Contributor(factor="Poor Dietary Pattern", rank=2, reason="Overlapping metabolic pathway")
            ],
            primary_drivers=["Obesity-related Cancer Risk"],
            causal_confidence="medium"
        )
        cf_obesity = CounterfactualPackage(
            scenarios=[
                Scenario(scenario_id="S_ob", change="Reduce BMI to healthy range (<25)", expected_effect="high", reasoning="Reduces chronic inflammatory markers"),
                Scenario(scenario_id="S_dt", change="Adopt a high-quality dietary pattern", expected_effect="medium", reasoning="Improves metabolic profile")
            ],
            comparisons=[]
        )
        sk_obesity = SkepticPackage(
            confidence="medium", uncertainties=[], limitations=[], conflicting_evidence=[], missing_information=[]
        )

        rep_obesity = generate_final_report(evidence_obesity, causality_obesity, cf_obesity, sk_obesity, profile_obesity)
        self.assertIn("predominantly lifestyle-related risk drivers", rep_obesity.evidence_summary)
        self.assertIn("Obesity-related Cancer Risk", rep_obesity.evidence_summary)
        self.assertIn("Reduce BMI to healthy range", rep_obesity.counterfactual_summary)

        # 4. BRCA Mutation Profile
        profile_brca = PatientProfile(
            session_id="brca", age=35, sex="female", bmi=22.0,
            smoking_status="never", smoking_years=0, alcohol_use="none",
            physical_activity="high", diet_quality="high", sun_exposure="low",
            occupation="office", environmental_exposure=[], family_history=True,
            known_mutations=["BRCA1"], previous_cancer_history=False
        )
        evidence_brca = EvidencePackage(
            risk_factors=[RiskFactor(factor="Genetic/Familial Predisposition", evidence_strength="high", evidence_score=0.98, source_count=10)],
            citations=[Citation(source="Nature Genetics", title="BRCA1 mutations", year=2017)],
            retrieved_documents=[]
        )
        causality_brca = CausalityPackage(
            ranked_contributors=[Contributor(factor="Genetic/Familial Predisposition", rank=1, reason="Inherited DNA repair deficiency")],
            primary_drivers=["Genetic/Familial Predisposition"],
            causal_confidence="high"
        )
        cf_brca = CounterfactualPackage(scenarios=[], comparisons=[])  # Non-modifiable factors should have no recommendations
        sk_brca = SkepticPackage(
            confidence="high", uncertainties=[], limitations=[], conflicting_evidence=[], missing_information=[]
        )

        rep_brca = generate_final_report(evidence_brca, causality_brca, cf_brca, sk_brca, profile_brca)
        self.assertIn("predominantly hereditary risk drivers", rep_brca.evidence_summary)
        self.assertIn("Type: Non-Modifiable", rep_brca.evidence_summary)

        # 5. Mixed Lifestyle Risk Profile
        profile_mixed = PatientProfile(
            session_id="mixed_life", age=42, sex="male", bmi=29.0,
            smoking_status="active", smoking_years=15, alcohol_use="heavy",
            physical_activity="low", diet_quality="low", sun_exposure="medium",
            occupation="office", environmental_exposure=[], family_history=False,
            known_mutations=[], previous_cancer_history=False
        )
        evidence_mixed = EvidencePackage(
            risk_factors=[
                RiskFactor(factor="Tobacco Smoke Exposure", evidence_strength="high", evidence_score=0.90, source_count=10),
                RiskFactor(factor="Alcohol Consumption Risk", evidence_strength="medium", evidence_score=0.75, source_count=6)
            ],
            citations=[Citation(source="Lancet", title="Lifestyle Factors", year=2020)],
            retrieved_documents=[]
        )
        causality_mixed = CausalityPackage(
            ranked_contributors=[
                Contributor(factor="Tobacco Smoke Exposure", rank=1, reason="Direct DNA damage"),
                Contributor(factor="Alcohol Consumption Risk", rank=2, reason="Synergistic mucosal permeability")
            ],
            primary_drivers=["Tobacco Smoke Exposure", "Alcohol Consumption Risk"],
            causal_confidence="high"
        )
        cf_mixed = CounterfactualPackage(
            scenarios=[
                Scenario(scenario_id="S_tb", change="Cessation of smoking", expected_effect="high", reasoning="Stops cumulative lung cell damage"),
                Scenario(scenario_id="S_alc", change="Abstain from heavy alcohol use", expected_effect="medium", reasoning="Avoids mucosal damage synergism")
            ],
            comparisons=[]
        )
        sk_mixed = SkepticPackage(
            confidence="high", uncertainties=["Potential Confounder: Co-occurrence of tobacco and alcohol"],
            limitations=[], conflicting_evidence=[], missing_information=[]
        )

        rep_mixed = generate_final_report(evidence_mixed, causality_mixed, cf_mixed, sk_mixed, profile_mixed)
        self.assertIn("predominantly lifestyle-related risk drivers", rep_mixed.evidence_summary)
        self.assertIn("Alcohol Consumption Risk", rep_mixed.evidence_summary)

        # 6. Previous Cancer History Profile
        profile_history = PatientProfile(
            session_id="prev_cancer", age=60, sex="male", bmi=24.0,
            smoking_status="never", smoking_years=0, alcohol_use="none",
            physical_activity="medium", diet_quality="high", sun_exposure="low",
            occupation="office", environmental_exposure=[], family_history=False,
            known_mutations=[], previous_cancer_history=True
        )
        evidence_history = EvidencePackage(
            risk_factors=[RiskFactor(factor="Previous Malignancy History", evidence_strength="high", evidence_score=0.88, source_count=5)],
            citations=[Citation(source="JCO", title="Prior malignancy follow-up", year=2022)],
            retrieved_documents=[]
        )
        causality_history = CausalityPackage(
            ranked_contributors=[Contributor(factor="Previous Malignancy History", rank=1, reason="Prior treatment and potential recurrence risk")],
            primary_drivers=["Previous Malignancy History"],
            causal_confidence="medium"
        )
        cf_history = CounterfactualPackage(scenarios=[], comparisons=[])
        sk_history = SkepticPackage(
            confidence="medium", uncertainties=[], limitations=[], conflicting_evidence=[], missing_information=[]
        )

        rep_history = generate_final_report(evidence_history, causality_history, cf_history, sk_history, profile_history)
        self.assertIn("predominantly mixed risk drivers", rep_history.evidence_summary) # Previous Malignancy falls back to mixed classification
        self.assertIn("Type: Non-Modifiable", rep_history.evidence_summary)


    def test_impact_tier_integration(self) -> None:
        """Verifies that synthesis report utilizes impact tiers and doesn't display raw percentages."""
        # Mix lifestyle profile but with explicit attribution
        from schemas.contracts import PatientProfile
        profile = PatientProfile(
            session_id="test_impact", age=42, sex="male", bmi=29.0,
            smoking_status="active", smoking_years=15, alcohol_use="heavy",
            physical_activity="low", diet_quality="low", sun_exposure="medium",
            occupation="office", environmental_exposure=[], family_history=False,
            known_mutations=[], previous_cancer_history=False
        )
        evidence = EvidencePackage(
            risk_factors=[
                RiskFactor(factor="Tobacco Smoke Exposure", evidence_strength="high", evidence_score=0.90, source_count=10)
            ],
            citations=[Citation(source="Lancet", title="Lifestyle Factors", year=2020)],
            retrieved_documents=[]
        )
        causality = CausalityPackage(
            ranked_contributors=[
                Contributor(
                    factor="Tobacco Smoke Exposure",
                    rank=1,
                    reason="Direct DNA damage",
                    attribution_percentage=35.0,
                    classification="Primary Driver",
                    impact_tier="Very High",
                    impact_bar="██████████"
                )
            ],
            primary_drivers=["Tobacco Smoke Exposure"],
            causal_confidence="high"
        )
        cf = CounterfactualPackage(scenarios=[], comparisons=[])
        sk = SkepticPackage(
            confidence="high", uncertainties=[], limitations=[], conflicting_evidence=[], missing_information=[]
        )

        report = generate_final_report(evidence, causality, cf, sk, profile)
        # Check that Very High and the visual bar are in the summary
        self.assertIn("Very High", report.evidence_summary)
        self.assertIn("██████████", report.evidence_summary)
        # Ensure raw percentage number (like "35.0%") is not in the text
        self.assertNotIn("35.0%", report.evidence_summary)


class TestImpactTierEngine(unittest.TestCase):
    """Test suite for the impact tier engine helper functions."""

    def test_classify_impact_tier(self) -> None:
        from tools.impact_tier import classify_impact_tier
        
        # Test boundaries
        self.assertEqual(classify_impact_tier(35.0), "Very High")
        self.assertEqual(classify_impact_tier(30.0), "Very High")
        self.assertEqual(classify_impact_tier(29.9), "High")
        self.assertEqual(classify_impact_tier(18.0), "High")
        self.assertEqual(classify_impact_tier(17.9), "Moderate")
        self.assertEqual(classify_impact_tier(10.0), "Moderate")
        self.assertEqual(classify_impact_tier(9.9), "Low")
        self.assertEqual(classify_impact_tier(5.0), "Low")
        self.assertEqual(classify_impact_tier(4.9), "Minimal")
        self.assertEqual(classify_impact_tier(0.0), "Minimal")

    def test_generate_visual_bar(self) -> None:
        from tools.impact_tier import generate_visual_bar
        
        self.assertEqual(generate_visual_bar(35.0), "██████████")
        self.assertEqual(generate_visual_bar(30.0), "██████████")
        self.assertEqual(generate_visual_bar(20.0), "████████")
        self.assertEqual(generate_visual_bar(15.0), "██████")
        self.assertEqual(generate_visual_bar(8.0), "████")
        self.assertEqual(generate_visual_bar(3.0), "██")

    def test_get_impact_color(self) -> None:
        from tools.impact_tier import get_impact_color
        
        self.assertEqual(get_impact_color(35.0), "red")
        self.assertEqual(get_impact_color(25.0), "orange")
        self.assertEqual(get_impact_color(15.0), "yellow")
        self.assertEqual(get_impact_color(7.0), "blue")
        self.assertEqual(get_impact_color(2.0), "green")


if __name__ == "__main__":
    unittest.main()

