"""Synthesis Agent implementation for CRRA.

Responsible for summarizing all analysis steps, listing citations and limitations,
and outputting the user-facing FinalReport with appropriate medical disclaimers.
"""

from schemas.contracts import AggregatedAnalysis, FinalReport


class SynthesisAgent:
    """Synthesis Agent that digests all analytical packages and produces a cohesive patient report."""

    def __init__(self) -> None:
        """Initialize the Synthesis Agent."""
        pass

    def run(self, analysis: AggregatedAnalysis) -> FinalReport:
        """Synthesizes the aggregated packages into a user-facing FinalReport.

        Args:
            analysis: The completed AggregatedAnalysis containing all previous agent packages.

        Returns:
            A FinalReport containing summaries, citations, limitations, and safety disclaimers.
        """
        # Collect top contributors names
        top_contribs = [c.factor for c in analysis.causality_package.ranked_contributors[:3]]

        # Generate summaries
        ev_summary = (
            "We identified several key contributors to cancer risk from current evidence, "
            f"primarily focusing on: {', '.join(top_contribs)}. Evidence levels vary but are "
            f"classified as having '{analysis.causality_package.causal_confidence}' confidence."
        )

        cf_scenarios = [s.change for s in analysis.counterfactual_package.scenarios]
        cf_summary = (
            f"Changing behavior or exposures can alter these risks. Hypothesized modifications "
            f"include: {', '.join(cf_scenarios)}. These may result in significant long-term risk reduction."
        )

        # Merge citations
        citations = analysis.evidence_package.citations

        # Merge limitations and uncertainties
        limitations = (
            analysis.skeptic_package.limitations
            + analysis.skeptic_package.uncertainties
        )

        disclaimer = (
            "Disclaimer: This report is generated by an artificial intelligence assistant "
            "for informational and educational purposes only. It is not medical advice, "
            "does not diagnose any condition, does not predict cancer probability, "
            "and does not replace consultation with a qualified healthcare professional."
        )

        return FinalReport(
            top_contributors=top_contribs,
            evidence_summary=ev_summary,
            counterfactual_summary=cf_summary,
            limitations=limitations,
            confidence=analysis.skeptic_package.confidence,
            citations=citations,
            safety_disclaimer=disclaimer,
        )
