"""synthesis.py

Synthesis tools for compiling clinical packages into user-facing FinalReport objects.
"""

from schemas.contracts import (
    EvidencePackage,
    CausalityPackage,
    CounterfactualPackage,
    SkepticPackage,
    FinalReport,
)


def generate_final_report(
    evidence: EvidencePackage,
    causality: CausalityPackage,
    counterfactual: CounterfactualPackage,
    skeptic: SkepticPackage,
) -> FinalReport:
    """Synthesizes the aggregated reasoning packages into a cohesive patient-facing FinalReport.

    Args:
        evidence: The EvidencePackage containing identified risk factors and citations.
        causality: The CausalityPackage detailing ranked contributors.
        counterfactual: The CounterfactualPackage containing generated what-if scenarios.
        skeptic: The SkepticPackage highlighting uncertainties and limitations.

    Returns:
        A FinalReport schema object.
    """
    # Collect top contributors names (top 3)
    top_contribs = [c.factor for c in causality.ranked_contributors[:3]]

    # Generate evidence summary
    ev_summary = (
        "We identified several key contributors to cancer risk from current evidence, "
        f"primarily focusing on: {', '.join(top_contribs)}. Evidence levels vary but are "
        f"classified as having '{causality.causal_confidence}' confidence."
    )

    # Generate counterfactual summary
    cf_scenarios = [s.change for s in counterfactual.scenarios]
    cf_summary = (
        f"Changing behavior or exposures can alter these risks. Hypothesized modifications "
        f"include: {', '.join(cf_scenarios)}. These may result in significant long-term risk reduction."
    )

    # Merge limitations and uncertainties from the skeptic audit
    limitations = skeptic.limitations + skeptic.uncertainties

    disclaimer = (
        "Disclaimer: This report is generated by an artificial intelligence assistant "
        "for informational and educational purposes only. It is not medical advice, "
        "does not diagnose any condition, does not predict cancer probability, "
        "and does not replace consultation with a qualified healthcare professional."
    )

    return FinalReport(
        top_contributors=top_contribs,
        evidence_summary=ev_summary,
        counterfactual_summary=cf_summary,
        limitations=limitations,
        confidence=skeptic.confidence,
        citations=evidence.citations,
        safety_disclaimer=disclaimer,
    )
